### ISSUE TITLE
yay -S --noedit is no more valid

### ISSUE THREAD

**Issue by SeeLook** [mdimura/docker-mingw-qt5#6]
Current yay doesn't support --noedit flag so README is misleading.

Still:
```
yay -S --noconfirm mingw-w64-fftw-bin mingw-w64-libogg mingw-w64-libvorbis-bin
```
Fails with:
error: failed retrieving file
under docker (gitlab)

**Comment by mdimura** [comment]
Thank you for spotting the `--noedit` issue! The error you get is due to an incorrect `source` URL in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-libvorbis-bin) of the `mingw-w64-libvorbis-bin` [AUR package](https://aur.archlinux.org/packages/mingw-w64-libvorbis-bin/). You might need to contact its maintainer or fix it directly if you know the right URL.
Without libvorbis, the command actually works:
```
yay -S --noconfirm mingw-w64-fftw-bin mingw-w64-libogg
```

**Comment by SeeLook** [comment]
Thank You for quick response and the clue.
And for docker in the first place...
I got it working that way:
```
before_script:
    - yay -S --noconfirm --noprogressbar --needed aur/mingw-w64-fftw-bin aur/mingw-w64-libogg aur/mingw-w64-libvorbis
```
